# Base configs
baseurl: "http://sbroec01.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Mindful Snaps Photography"
subtitle: "More than just images..."
author: "Stephan Broecker"
header:
 title: "Mindful Snaps Photography  "
 subtitle: "images"
footer:
 name: "Mindful Snaps Photography"
 bio: "All Images Copyright (C) Stephan Broecker."
 github: "Created using the <a href=\"https://github.com/ramswaroop/photography\">Photography project by Ram Swaroop on GitHub</a> - thanks Ram!"
social_urls:
  facebook: "https://www.facebook.com//stephan.broecker"
  instagram: "https://www.instagram.com/mindful_snaps_photography/"
  github: "https://www.github.com/sbroec01"
